### PR TITLE
ci: setup integration apps

### PR DESCRIPTION
**Pull request by arturovt**
Depends on #4

### CODE REVIEW

**Review by internettrans — APPROVED** [review]

**Comment by internettrans** [comment]
I merged in master to this branch after having merged in #4, so that the diff would easier to read. Looks like the build is failing now due to eslint errors in the integration app

**Comment by arturovt** [comment]
I will fix it. I will rebase on master first of all.

**Comment by internettrans** [comment]
Is this ready to mark as ready for merge? If so I will merge this.

**Comment by arturovt** [comment]
No, it’s not, sorry. I’m stuck at work but I’m planning to finish it this week.

**Comment by arturovt** [comment]
@joeldenning ping

**Review by internettrans — APPROVED** [review]
Thanks for your work on this.

**Comment by internettrans** [comment]
Shall we publish single-spa-aurelia to npm? Is there anything else that needs to be done first?

**Pull request merged**
